#include "Bot.h"

const int ECHOES = 2;

const command INPUTS[] = {
	// Setup controller
						{ NOTHING,  150 },
	{ TRIGGERS,   5 },	{ NOTHING,  150 },
	{ TRIGGERS,   5 },	{ NOTHING,  150 },
	{ A,          5 },	{ NOTHING,  100 },

	// Open game
	{ HOME,       5 },	{ NOTHING,  100 },
	{ A,          5 },	{ NOTHING,  100 },

	// #### ROW A ####
	// 1
	{ A,          5 },	{ NOTHING,   30 }, // Selects A1
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 2
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 3
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 4
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 5
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 6
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },

	// #### ROW B ####
	// 1
	{ DOWN,       5 },	{ NOTHING,   10 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 2
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 3
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 4
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 5
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 6
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },

	// #### ROW C ####
	// 1
	{ DOWN,       5 },	{ NOTHING,   10 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 2
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 3
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 4
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 5
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 6
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },

	// #### ROW D ####
	// 1
	{ DOWN,       5 },	{ NOTHING,   10 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 2
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 3
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 4
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 5
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 6
	{ LEFT,       5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },

	// #### ROW E ####
	// 1
	{ DOWN,       5 },	{ NOTHING,   10 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 2
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 3
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 4
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 5
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },
	// 6
	{ RIGHT,      5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   30 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   50 },
	{ UP,         5 },	{ NOTHING,    5 },
	{ A,          5 },	{ NOTHING,   70 },
	{ A,          5 },	{ NOTHING,   50 },

	// end
	{ NOTHING,   -1 }
};

const int INPUT_REPEAT_BEGIN = 11;
const int INPUTS_LENGTH = sizeof(INPUTS)/sizeof(command);
