from typing import Any


class Serial:
    def __init__(self, p: str, d: int) -> None: ...
    def __enter__(self) -> Serial: ...
    def __exit__(self, *a: Any) -> bool | None: ...
    def write(self, bts: bytes) -> int: ...
    @property
    def in_waiting(self) -> bool: ...
    def read(self) -> bytes: ...
